r"""build_explorables.py — generate the interactive "explorable" pages.

These are bespoke, dependency-free pages where a reader drags a slider and a chart
redraws *live* — the same simulations the notebooks run, but instant and in pure
JavaScript over real data embedded at build time. No kernel, no server, offline.

It writes:
  * rendered/assets/explorables-data.js  — real populations + an exact t* table
  * rendered/explore-confidence-intervals.html  (the flagship 100-CI coverage demo)
  * rendered/explore-clt.html                   (the Central Limit Theorem sampler)
  * rendered/explore-p-value.html               (p-values, errors & power)

    ..\.venv\Scripts\python.exe tools\build_explorables.py

Reads raw/ only. The widgets themselves live in rendered/assets/explorables.js.
"""
import json
import pathlib

import numpy as np
import pandas as pd
from scipy import stats

ROOT = pathlib.Path(__file__).resolve().parent.parent
RAW = ROOT / "raw"
RENDERED = ROOT / "rendered"
ASSETS = RENDERED / "assets"

SITE = "Statistics, by seeing it happen"


def _pop(values, name, unit):
    v = np.asarray(values, dtype=float)
    v = v[~np.isnan(v)]
    return {"name": name, "unit": unit, "values": [round(float(x), 2) for x in v],
            "mean": round(float(v.mean()), 2), "sd": round(float(v.std(ddof=0)), 2),
            "n": int(v.size)}


def build_data():
    ames = pd.read_csv(RAW / "ames.csv")
    gap = pd.read_csv(RAW / "gapminder.csv")
    life07 = gap.loc[gap["year"] == 2007, "lifeExp"]

    pops = {
        "ames_area": _pop(ames["area"].astype(int), "House sizes (Ames, sq ft)", "sq ft"),
        "life_exp": _pop(life07, "Life expectancy, 2007 (years)", "years"),
    }

    # Exact two-sided t* for each confidence level and degrees of freedom 1..299
    # (index i -> df = i+1), so the in-browser CI matches scipy exactly.
    levels = [0.80, 0.90, 0.95, 0.99]
    dfs = list(range(1, 300))
    tcrit = {str(int(L * 100)): [round(float(stats.t.ppf(1 - (1 - L) / 2, df)), 4) for df in dfs]
             for L in levels}

    data = {"pops": pops, "tcrit": tcrit, "tcrit_max_df": dfs[-1]}
    ASSETS.mkdir(parents=True, exist_ok=True)
    (ASSETS / "explorables-data.js").write_text(
        "// Generated by tools/build_explorables.py — real data for the explorables.\n"
        "window.SC_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    print(f"wrote assets/explorables-data.js  "
          f"(ames n={pops['ames_area']['n']}, life n={pops['life_exp']['n']})")


PAGE = """<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="{desc}">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:image" content="https://jd-jones-ases.github.io/seeing-statistics/assets/og-card.png">
<meta name="theme-color" content="#4c72b0">
<link rel="icon" href="assets/favicon.svg">
<link rel="stylesheet" href="assets/vendor/katex/katex.min.css">
<link rel="stylesheet" href="assets/course.css">
<link rel="stylesheet" href="assets/explorables.css">
<title>{title} · {site}</title>
<script>(function(){{var t;try{{t=localStorage.getItem('sc-theme')}}catch(e){{}}if(t)document.documentElement.setAttribute('data-theme',t);}})();</script>
</head><body>
<div class="sc-topbar">
  <a class="sc-home" href="index.html">{site} <span>· course map</span></a>
  <span class="sc-spacer"></span>
  <span class="sc-pos" style="color:var(--sc-muted);font-size:12.5px">interactive explorable</span>
  <button class="sc-btn" type="button" onclick="scToggleTheme()" aria-label="Toggle light or dark theme">◐</button>
</div>
<main class="explore-wrap">
  <h1>{title}</h1>
  {intro}
  <div id="explorable" data-kind="{kind}" data-pagefind-ignore></div>
  {after}
</main>
<footer class="sc-footer">
  <p><b>How this works:</b> everything above is computed live in your browser in plain
  JavaScript over the real dataset — no server, no Python, nothing uploaded. The
  companion lesson runs the same simulation in Python you can edit.</p>
  <p>© JD Jones, 2026 · <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a> ·
  <a href="index.html">↑ Course map</a> · <a href="{lesson}">Open the companion lesson →</a></p>
</footer>
<script defer src="assets/vendor/katex/katex.min.js"></script>
<script defer src="assets/vendor/katex/contrib/auto-render.min.js"></script>
<script defer src="assets/course.js"></script>
<script defer src="assets/explorables-data.js"></script>
<script defer src="assets/explorables.js"></script>
</body></html>
"""

PAGES = [
    dict(
        file="explore-confidence-intervals.html",
        kind="ci",
        title="Watch 100 confidence intervals",
        desc="Drag the sample size and confidence level and watch ~95 of 100 intervals capture the true mean — live, on real data.",
        lesson="12-confidence-intervals.html",
        intro="""<p>A 95% confidence interval doesn't promise that <em>this</em> interval contains the
truth — it promises that the <strong>recipe</strong> catches the true mean about 95% of the time. Here you can
<strong>watch that happen</strong>. We treat a whole real dataset as the population (so we know the true mean
\\(\\mu\\)), draw 100 samples, and build an interval from each:</p>
<p style="text-align:center">\\[ \\bar{x} \\;\\pm\\; t^{*}\\,\\frac{s}{\\sqrt{n}} \\]</p>
<p>Teal solid intervals (●) caught \\(\\mu\\); orange-red dashed ones (✕) missed. Drag the sliders and draw fresh
samples — does the hit rate track the confidence level?</p>""",
        after="""<p class="explore-note">Try it: shrink <b>n</b> toward 5 — intervals get wider (and a touch
less reliable on skewed data). Raise the <b>confidence level</b> — the net widens to catch more. The miss rate
should hover near <em>(100 − level)%</em>, no matter the sample.</p>""",
    ),
    dict(
        file="explore-clt.html",
        kind="clt",
        title="The Central Limit Theorem, by hand",
        desc="Pick a wildly non-normal population, drag the sample size, and watch the distribution of the sample mean turn into a bell curve.",
        lesson="10-sampling-distributions-clt.html",
        intro="""<p>The engine under the whole second half of the course: no matter how lopsided the
population, the <strong>average of a sample</strong> piles up into a tidy bell curve centred on the true mean,
with spread \\(\\sigma/\\sqrt{n}\\). Pick a population, drag the sample size \\(n\\), and watch it happen.</p>""",
        after="""<p class="explore-note">Try it: start at <b>n = 1</b> (the sampling distribution is just the
population — as skewed as ever), then climb. By <b>n = 30</b> even the most lopsided population averages into a
near-perfect bell, and the spread shrinks by the \\(\\sqrt{n}\\) law.</p>""",
    ),
    dict(
        file="explore-p-value.html",
        kind="power",
        title="p-values, errors & power",
        desc="Drag the true effect size and the significance level to see Type I and Type II error and the power of a test trade off in real time.",
        lesson="13-hypothesis-testing.html",
        intro="""<p>A hypothesis test draws a line in the sand. The <strong>null</strong> world (no effect)
is the blue curve; the <strong>true</strong> world (a real effect of size \\(\\delta\\), in standard-error units)
is the orange curve. We reject the null when the test statistic lands past the critical value set by
\\(\\alpha\\). Drag the pieces and watch the four outcomes trade off.</p>""",
        after="""<p class="explore-note">Try it: with \\(\\delta = 0\\) (no real effect), the reject rate is
exactly \\(\\alpha\\) — that's the Type I error rate. Slide \\(\\delta\\) up, or lower \\(\\alpha\\): power
(catching a real effect) rises with effect size and sample size, and falls as you demand stricter evidence.</p>""",
    ),
]


def build_pages():
    for p in PAGES:
        html = PAGE.format(site=SITE, **p)
        (RENDERED / p["file"]).write_text(html, encoding="utf-8")
        print(f"wrote rendered/{p['file']}")


if __name__ == "__main__":
    build_data()
    build_pages()
    print("explorables built.")
