r"""make_reference.py — build the glossary, the printable formula cheat-sheet, and
the per-lesson quiz data, from a JSON bundle authored by the content workflow.

    ..\.venv\Scripts\python.exe tools\make_reference.py [path-to-json]

The JSON has the shape {glossary:{terms:[...]}, formulas:{groups:[...]},
quizzes:[{id, questions:[...]}, ...]}. Outputs:
  rendered/glossary.html, rendered/formula-sheet.html, rendered/assets/quizzes-data.js
"""
import html
import json
import sys
import pathlib

import pagekit

ROOT = pathlib.Path(__file__).resolve().parent.parent
RENDERED = ROOT / "rendered"
DEFAULT_JSON = ROOT / "tools" / "_reference.json"


def build_glossary(terms):
    items = []
    for t in terms:
        see = (f' <span class="see">→ {html.escape(t["see"])}</span>' if t.get("see") else "")
        items.append(
            f'<div class="gl" data-term="{html.escape((t["term"]+" "+t["definition"]).lower())}">'
            f'<dt>{html.escape(t["term"])}</dt>'
            f'<dd>{html.escape(t["definition"])}{see}</dd></div>')
    body = f"""
<h1>Glossary</h1>
<p>Plain-English definitions of the {len(terms)} ideas this course leans on most. Type to filter.</p>
<input id="glf" type="search" placeholder="filter terms…" aria-label="filter glossary terms"
  style="width:100%;max-width:360px;padding:8px 12px;border:1px solid var(--sc-line);border-radius:9px;
  background:var(--sc-card);color:var(--sc-ink);margin:6px 0 14px">
<dl class="glossary">{''.join(items)}</dl>
<style>
.glossary{{margin:0}} .gl{{border-bottom:1px solid var(--sc-line);padding:10px 2px}}
.gl dt{{font-weight:700;color:var(--sc-ink);font-size:16px}}
.gl dd{{margin:.2em 0 0;color:var(--sc-muted);font-size:14.5px}}
.gl .see{{color:var(--sc-accent);font-size:12.5px;white-space:nowrap}}
</style>
<script>
(function(){{var f=document.getElementById('glf');if(!f)return;
f.addEventListener('input',function(){{var q=f.value.toLowerCase();
document.querySelectorAll('.gl').forEach(function(g){{g.style.display=g.dataset.term.indexOf(q)>=0?'':'none';}});}});}})();
</script>
"""
    RENDERED.joinpath("glossary.html").write_text(
        pagekit.page("Glossary", "Plain-English definitions of the key statistics terms in the course.",
                     body, label="glossary"), encoding="utf-8")
    print(f"wrote rendered/glossary.html  ({len(terms)} terms)")


def build_formulas(groups):
    secs = []
    total = 0
    for g in groups:
        rows = []
        for it in g["items"]:
            total += 1
            note = (f'<div class="note">{html.escape(it["note"])}</div>' if it.get("note") else "")
            rows.append(f'<div class="fm"><div class="nm">{html.escape(it["name"])}</div>'
                        f'<div class="eq">\\[{it["latex"]}\\]</div>{note}</div>')
        secs.append(f'<section><h2>{html.escape(g["title"])}</h2>{"".join(rows)}</section>')
    body = f"""
<h1>Formula cheat-sheet</h1>
<p class="noprint">The {total} formulas the course uses most, in one place. Use the <b>Print</b> button (top right)
to save a copy.</p>
<div class="sheet">{''.join(secs)}</div>
<style>
.sheet section{{margin:0 0 14px}} .sheet h2{{font-size:16px;color:var(--sc-accent);border-bottom:1px solid var(--sc-line);
  padding-bottom:3px;margin:14px 0 8px}}
.fm{{display:grid;grid-template-columns:200px 1fr;gap:10px;align-items:baseline;padding:5px 0}}
.fm .nm{{font-size:14px;color:var(--sc-muted)}} .fm .eq{{font-size:15px;overflow-x:auto}}
.fm .note{{grid-column:1/-1;font-size:12.5px;color:var(--sc-muted);margin:-2px 0 0}}
@media (max-width:560px){{.fm{{grid-template-columns:1fr}}}}
@media print{{.noprint,.sc-topbar,.sc-footer{{display:none!important}} body{{background:#fff;color:#000}}
  .sheet{{column-count:2;column-gap:26px}} .fm{{break-inside:avoid}}}}
</style>
"""
    RENDERED.joinpath("formula-sheet.html").write_text(
        pagekit.page("Formula cheat-sheet", "The key probability & statistics formulas the course uses, printable.",
                     body, label="formula sheet", math=True, print_btn=True), encoding="utf-8")
    print(f"wrote rendered/formula-sheet.html  ({total} formulas)")


def build_quizzes(quizzes):
    table = {q["id"]: q["questions"] for q in quizzes if q.get("questions")}
    out = ("// Generated by tools/make_reference.py — per-lesson self-check quizzes.\n"
           "window.SC_QUIZ = " + json.dumps(table, separators=(",", ":")) + ";\n")
    RENDERED.joinpath("assets", "quizzes-data.js").write_text(out, encoding="utf-8")
    n = sum(len(v) for v in table.values())
    print(f"wrote rendered/assets/quizzes-data.js  ({len(table)} lessons, {n} questions)")


def main(argv):
    path = pathlib.Path(argv[0]) if argv else DEFAULT_JSON
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("glossary", {}).get("terms"):
        build_glossary(data["glossary"]["terms"])
    if data.get("formulas", {}).get("groups"):
        build_formulas(data["formulas"]["groups"])
    if data.get("quizzes"):
        build_quizzes(data["quizzes"])
    print("reference build done.")


if __name__ == "__main__":
    main(sys.argv[1:])
